---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vmstorage
  name: vmstorage
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - port: 8482
      targetPort: http
      protocol: TCP
      name: http
    - port: 8401
      targetPort: vmselect
      protocol: TCP
      name: vmselect
    - port: 8400
      targetPort: vminsert
      protocol: TCP
      name: vminsert
  selector:
    app: vmstorage
