- job_name: "traefik-monitor-stg"
  ec2_sd_configs:
    - region: ap-east-1
      port: 8888
      filters:
        - name: tag:Name
          values:
            - GS-stg
  metrics_path: /metrics
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - target_label: "env"
      replacement: stg
