- job_name: "traefik-monitor"
  metrics_path: /metrics
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
  static_configs:
    - targets:
        - 10.10.20.48:8888
      labels:
        env: stg
