---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm
  namespace: monitoring
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vm-cluster-role
rules: []
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vm-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: vm
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: vm-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vm-role
  namespace: monitoring
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vm-role-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vm-role
subjects:
  - kind: ServiceAccount
    name: vm
    namespace: monitoring
