apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - deployment.yaml
  - service.yaml
  - rbac.yaml
  - ingress.yaml
patches:
  - target:
      kind: Ingress
      name: vmselect
    patch: |-
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1security-groups
        value: "whitelist,Public_Access"
