---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vmselect-oidc-role
  namespace: monitoring
rules:
  - apiGroups:
      - ""
    resourceNames:
      - vmselect-secret
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vmselect-oidc-rolebind
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vmselect-oidc-role
subjects:
  - kind: ServiceAccount
    name: aws-load-balancer-controller
    namespace: kube-system
