apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: vmagent-config
    files:
      - config.yaml=./conf/config.yaml
  - name: vmagent-jobs
    files:
      - cloudwatch.yaml=./jobs/cloudwatch.yaml
      - container-cadvisor.yaml=./jobs/container-cadvisor.yaml
      - dotnet-metrics.yaml=./jobs/dotnet-metrics.yaml
      - fluentd.yaml=./jobs/fluentd.yaml
      - k8s.yaml=./jobs/k8s.yaml
      - keda.yaml=./jobs/keda.yaml
      - mysql.yaml=./jobs/mysql.yaml
      - node-exporter.yaml=./jobs/node-exporter.yaml
      - process-exporter.yaml=./jobs/process-exporter.yaml
      - rabbitmq.yaml=./jobs/rabbitmq.yaml
      - redis.yaml=./jobs/redis.yaml
      - vm.yaml=./jobs/vm.yaml
