---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vmauth
  name: vmauth
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: vmauth
  replicas: 1
  template:
    metadata:
      labels:
        app: vmauth
    spec:
      automountServiceAccountToken: true
      containers:
        - name: vmauth
          image: "victoriametrics/vmauth:v1.95.1"
          imagePullPolicy: "IfNotPresent"
          securityContext: {}
          args:
            - --auth.config=/vmauth/auth.yaml
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
          ports:
            - name: http
              containerPort: 8427
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: vmauth-config
              mountPath: /vmauth
          resources: {}
      volumes:
        - name: vmauth-config
          configMap:
            name: vmauth-config
