---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vmauth
  name: vmauth
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - port: 8427
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vmauth
