---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vmalert
  name: vmalert
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: vmalert
  replicas: 1
  template:
    metadata:
      labels:
        app: vmalert
    spec:
      automountServiceAccountToken: true
      containers:
        - name: vmalert
          image: victoriametrics/vmalert:v1.95.1
          imagePullPolicy: "IfNotPresent"
          securityContext: {}
          args:
            - --datasource.url=http://vmselect:8481/select/0/prometheus/
            - --remoteRead.url=http://vmselect:8481/select/0/prometheus/
            - --remoteWrite.url=https://metrics-collector.v16cp.me/insert/0/prometheus/
            - --notifier.url=http://alertmanager:9093
            - --rule=/vmalert/rules/*.yaml
            - --envflag.enable=true
            - --envflag.prefix=VM_
            - --loggerFormat=json
            - --configCheckInterval=1m
            - --loggerFormat=json
            - --loggerLevel=ERROR
          ports:
            - name: http
              containerPort: 8880
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: vmalert-rules
              mountPath: /vmalert/rules
          resources: {}
          envFrom:
            - secretRef:
                name: vmalert-secret
      volumes:
        - name: vmalert-rules
          configMap:
            name: vmalert-rules
