apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - deployment.yaml
  - service.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: vmalert-rules
    files:
      - alert-rule.yaml=./conf/alert-rule.yaml
      - record-rule.yaml=./conf/record-rule.yaml
