---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vmalert
  name: vmalert
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - port: 8880
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vmalert
