apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: vmagent-config
    files:
      - config.yaml=./conf/config.yaml
  - name: vmagent-jobs
    files:
      - cloudwatch.yaml=./jobs/cloudwatch.yaml
      - container-cadvisor.yaml=./jobs/container-cadvisor.yaml
      - dotnet.yaml=./jobs/dotnet.yaml
      - domain-exporter.yaml=./jobs/domain-exporter.yaml
      - fluentd.yaml=./jobs/fluentd.yaml
      - http.yaml=./jobs/http.yaml
      - k8s.yaml=./jobs/k8s.yaml
      - keda.yaml=./jobs/keda.yaml
      - mysql.yaml=./jobs/mysql.yaml
      - node-exporter.yaml=./jobs/node-exporter.yaml
      - rabbitmq.yaml=./jobs/rabbitmq.yaml
      - redis.yaml=./jobs/redis.yaml
      - vm.yaml=./jobs/vm.yaml

patches:
  - target:
      kind: Ingress
      name: vmagent
    patch: |-
      - op: add
        path: /metadata/annotations/alb.ingress.kubernetes.io~1load-balancer-name
        value: infra-internal
      - op: add
        path: /metadata/annotations/alb.ingress.kubernetes.io~1group.name
        value: infra-internal
      - op: replace
        path: /spec/rules/0/host
        value: metric-sources-prod.v16cp.me
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1security-groups
        value: eks-cluster-sg,monitoring-white-list,prod-internal-sg
