apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../base

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: vmagent-config
    files:
      - config.yaml=./conf/config.yaml
  - name: vmagent-jobs
    files:
      - cloudwatch.yaml=./jobs/cloudwatch.yaml
      - container-cadvisor.yaml=./jobs/container-cadvisor.yaml
      - dotnet.yaml=./jobs/dotnet.yaml
      - domain-exporter.yaml=./jobs/domain-exporter.yaml
      - fluentd.yaml=./jobs/fluentd.yaml
      - http.yaml=./jobs/http.yaml
      - k8s.yaml=./jobs/k8s.yaml
      - keda.yaml=./jobs/keda.yaml
      - mysql.yaml=./jobs/mysql.yaml
      - node-exporter.yaml=./jobs/node-exporter.yaml
      - rabbitmq.yaml=./jobs/rabbitmq.yaml
      - redis.yaml=./jobs/redis.yaml
      - vm.yaml=./jobs/vm.yaml

patches:
  - target:
      kind: Deployment
      name: vmagent
    patch: |-
      - op: add
        path: "/spec/template/metadata/annotations/vaultpy.io~1target-resource-type"
        value: secret
      - op: add
        path: "/spec/template/metadata/annotations/vaultpy.io~1target-resource-name"
        value: vmagent-secret
      - op: add
        path: "/spec/template/metadata/annotations/vaultpy.io~1kv2-name"
        value: v16-devops
      - op: add
        path: "/spec/template/metadata/annotations/vaultpy.io~1kv2-path"
        value: /monitoring/victoriametrics/prod/vmagent/secret
  - target:
      kind: Ingress
      name: vmagent
    patch: |-
      - op: add
        path: /metadata/annotations/alb.ingress.kubernetes.io~1load-balancer-name
        value: internaloidc
      - op: add
        path: /metadata/annotations/alb.ingress.kubernetes.io~1group.name
        value: internal-oidc
      - op: add
        path: /metadata/annotations/alb.ingress.kubernetes.io~1auth-type
        value: oidc
      - op: add
        path: /metadata/annotations/alb.ingress.kubernetes.io~1auth-idp-oidc
        value: '{"issuer":"https://keycloak.v16cp.me/auth/realms/master","authorizationEndpoint":"https://keycloak.v16cp.me/auth/realms/master/protocol/openid-connect/auth","tokenEndpoint":"https://keycloak.v16cp.me/auth/realms/master/protocol/openid-connect/token","userInfoEndpoint":"https://keycloak.v16cp.me/auth/realms/master/protocol/openid-connect/userinfo","secretName":"vmagent-secret"}'
      - op: replace
        path: /spec/rules/0/host
        value: metric-sources-prod.v16cp.me
      - op: replace
        path: /metadata/annotations/alb.ingress.kubernetes.io~1security-groups
        value: eks-cluster-sg,monitoring-white-list,prod-internal-sg
